/* Processed by ecpg (4.9.0) */
/* These include files are added by the preprocessor */
#include <ecpglib.h>
#include <ecpgerrno.h>
#include <sqlca.h>
/* End of automatic include section */

#line 1 "sample.pgc"
/*
 * File - "sample.cpp"
 * Desc - This is the sample program generated by our engine.
 *
 * Steps to run this program : 
 *  1. Log in to PostgreSQL server (ssh [username]@postgres.cs.stevens.edu).
 *  2. In the program (L48), modify [dbname], [username], [password] to
 *     yours ([dbname] is the same as your [username] by default).
 *  3. Preprocessor - $ ecpg -I /usr/include/postgresql sample.pgc
 *  4. Compile      - $ g++ -c -I /usr/include/postgresql/ sample.c
 *  5. Link         - $ g++ -L /usr/include/postgresql/ sample.o -lecpg -o sample
 *  6. Execute      - $ ./sample
 */

#include <stdio.h>
#include <stdlib.h>
#include <vector>
#include <iostream>

using namespace std;

/* exec sql begin declare section */
  
		
		
	    
	    
		 
		
		 

  
struct Sal { 
#line 24 "sample.pgc"
 char * cust ;
 
#line 25 "sample.pgc"
 char * prod ;
 
#line 26 "sample.pgc"
 short dd ;
 
#line 27 "sample.pgc"
 short mm ;
 
#line 28 "sample.pgc"
 short yy ;
 
#line 29 "sample.pgc"
 char * state ;
 
#line 30 "sample.pgc"
 long quant ;
 } ; 
#line 32 "sample.pgc"
 struct Sal sale_rec ;
/* exec sql end declare section */
#line 33 "sample.pgc"


#line 1 "/usr/include/postgresql/sqlca.h"
#ifndef POSTGRES_SQLCA_H
#define POSTGRES_SQLCA_H

#ifndef PGDLLIMPORT
#if  defined(WIN32) || defined(__CYGWIN__)
#define PGDLLIMPORT __declspec (dllimport)
#else
#define PGDLLIMPORT
#endif   /* __CYGWIN__ */
#endif   /* PGDLLIMPORT */

#define SQLERRMC_LEN	150

#ifdef __cplusplus
extern		"C"
{
#endif

struct sqlca_t
{
	char		sqlcaid[8];
	long		sqlabc;
	long		sqlcode;
	struct
	{
		int			sqlerrml;
		char		sqlerrmc[SQLERRMC_LEN];
	}			sqlerrm;
	char		sqlerrp[8];
	long		sqlerrd[6];
	/* Element 0: empty						*/
	/* 1: OID of processed tuple if applicable			*/
	/* 2: number of rows processed				*/
	/* after an INSERT, UPDATE or				*/
	/* DELETE statement					*/
	/* 3: empty						*/
	/* 4: empty						*/
	/* 5: empty						*/
	char		sqlwarn[8];
	/* Element 0: set to 'W' if at least one other is 'W'	*/
	/* 1: if 'W' at least one character string		*/
	/* value was truncated when it was			*/
	/* stored into a host variable.             */

	/*
	 * 2: if 'W' a (hopefully) non-fatal notice occurred
	 */	/* 3: empty */
	/* 4: empty						*/
	/* 5: empty						*/
	/* 6: empty						*/
	/* 7: empty						*/

	char		sqlstate[5];
};

struct sqlca_t *ECPGget_sqlca(void);

#ifndef POSTGRES_ECPG_INTERNAL
#define sqlca (*ECPGget_sqlca())
#endif

#ifdef __cplusplus
}
#endif

#endif

#line 34 "sample.pgc"


vector<struct Sal> abc;
//----------------------------------------------------------------------
// FUNCTION PROTOTYPE declaration
//----------------------------------------------------------------------
void	output_record(); //output records to the console

//----------------------------------------------------------------------
int main(int argc, char* argv[])
//----------------------------------------------------------------------
{
   //----------------------------------------------------------------------
   // DATABASE CONNECTION
   //----------------------------------------------------------------------
   { ECPGconnect(__LINE__, 0, "cs562@localhost:5432" , "postgres" , "cs562" , NULL, 0); }
#line 49 "sample.pgc"

   /* exec sql whenever sqlerror  sqlprint ; */
#line 50 "sample.pgc"


   //----------------------------------------------------------------------
   // PRINT TITLE
   //----------------------------------------------------------------------   
   cout << " CUST  | PROD    | DAY | MON | YEAR | STATE | QUANT \n";
   cout << "-------+---------+-----+-----+------+-------+-------\n";
   
   //----------------------------------------------------------------------
   // READ RECORDS
   //----------------------------------------------------------------------
   /* declare mycursor cursor for select * from sales */
#line 61 "sample.pgc"

   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "set transaction read only", ECPGt_EOIT, ECPGt_EORT);
#line 62 "sample.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 62 "sample.pgc"

   // Open cursor
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "declare mycursor cursor for select * from sales", ECPGt_EOIT, ECPGt_EORT);
#line 64 "sample.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 64 "sample.pgc"

   // Fetch Data
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "fetch from mycursor", ECPGt_EOIT, 
	ECPGt_char,&(sale_rec.cust),(long)0,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_char,&(sale_rec.prod),(long)0,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_short,&(sale_rec.dd),(long)1,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_short,&(sale_rec.mm),(long)1,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_short,&(sale_rec.yy),(long)1,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_char,&(sale_rec.state),(long)0,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.quant),(long)1,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, ECPGt_EORT);
#line 66 "sample.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 66 "sample.pgc"
 //fetch the first row
   while (sqlca.sqlcode == 0) {
      output_record();
      abc.push_back(sale_rec);
      { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "fetch from mycursor", ECPGt_EOIT, 
	ECPGt_char,&(sale_rec.cust),(long)0,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_char,&(sale_rec.prod),(long)0,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_short,&(sale_rec.dd),(long)1,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_short,&(sale_rec.mm),(long)1,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_short,&(sale_rec.yy),(long)1,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_char,&(sale_rec.state),(long)0,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.quant),(long)1,(long)1,sizeof( struct Sal ), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, ECPGt_EORT);
#line 70 "sample.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 70 "sample.pgc"
 //fetch the rest rows
   }
   // Close cursor
printf(" %-5s |",abc[497].cust);
printf(" %-7s |",abc[497].prod); 
cout<<"|"<<abc[497].dd<<"|"<<abc[497].mm<<"|"<<abc[497].yy<<"|"<<abc[497].quant<<endl;
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "close mycursor", ECPGt_EOIT, ECPGt_EORT);
#line 76 "sample.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 76 "sample.pgc"


   return 0;
}

//----------------------------------------------------------------------
void	output_record()  //set of output
//----------------------------------------------------------------------
{
	printf(" %-5s |",sale_rec.cust);   // Customer
	printf(" %-7s |",sale_rec.prod);   // Product
	printf("  %2d |",sale_rec.dd);     // Day
	printf("  %2d |",sale_rec.mm);     // Month
	printf(" %4d |",sale_rec.yy);      // Year
	printf(" %-5s |",sale_rec.state);  // State
	printf(" %5d \n",sale_rec.quant);  // Quantity
}
